apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: services.serving.knative.dev
spec:
  group: serving.knative.dev
  names:
    categories:
    - all
    - knative
    - serving
    kind: Service
    listKind: ServiceList
    plural: services
    shortNames:
    - kservice
    - ksvc
    singular: service
  scope: Namespaced
  version: v1alpha1
status:
  acceptedNames:
    categories:
    - all
    - knative
    - serving
    kind: Service
    listKind: ServiceList
    plural: services
    shortNames:
    - kservice
    - ksvc
    singular: service