---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - runtime.kyma-project.io
  resources:
  - functions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - runtime.kyma-project.io
  resources:
  - functions/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - ""
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - create
  - get
  - delete
  - list
  - update
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: manager-role
  namespace: default
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
spec:
  selector:
    matchLabels:
      app: runtime-controller
  serviceName: runtime
  template:
    metadata:
      labels:
        app: runtime-controller
    spec:
      serviceAccount: manager-role
      containers:
      # Change the value of image field below to your controller image URL
      - image: runtime-controller
        imagePullPolicy: IfNotPresent
        name: manager-role
        env: 
        - name: CONTROLLER_CONFIGMAP
          value: "controller-config"
        - name: CONTROLLER_CONFIGMAP_NS
          value: "kyma-system"


